/* eslint-disable */
module.exports = {
   /* key : label */
   "Drag and drop or click here": "Drag and drop or click here",
   "Attach an image to this object.": "Attach an image to this object.",
   "Image Attachment": "Image Attachment",
   "No more tasks...good job!": "No more tasks...good job!",
   "Your Tasks": "Your Tasks",
   "No tasks...you're all caught up.": "No tasks...you're all caught up.",
   "Inbox": "Inbox",
   "OK": "OK",
   "Alert": "Alert",
   "No rows were effected.  This does not seem right.":
      "No rows were effected.  This does not seem right.",
   "Do you want to delete this row?": "Do you want to delete this row?",
   "Delete data": "Delete data",
   " no": " no",
   " yes": " yes",
   "Send a custom email": "Send a custom email",
   "Redirect to another website URL": "Redirect to another website URL",
   "Close the current popup": "Close the current popup",
   "Redirect to the parent page": "Redirect to the parent page",
   "Redirect to an existing page": "Redirect to an existing page",
   "Message": "Message",
   "Show a confirmation message": "Show a confirmation message",
   "Select items": "Select items",
   "Select item": "Select item",
   "Sort": "Apply sort",
   "Filters": "Add filters",
   "Reset Filter": "Reset Filter",
   "To": "To",
   "Set": "Set",
   "Add field to edit": "Add field to edit",
   "Expand Menu": "Expand Menu",
   "Collapse Menu": "Collapse Menu",
   "does not contain current user": "does not contain current user",
   "contains current user": "contains current user",
   "is not current user": "is not current user",
   "is current user": "is current user",
   "is not checked": "is not checked",
   "is checked": "is checked",
   "does not equal": "does not equal",
   "equals": "equals",
   "≥": "≥",
   "≤": "≤",
   ">": ">",
   "<": "<",
   "≠": "≠",
   ":": "=",
   "next ... days": "next ... days",
   "last ... days": "last ... days",
   "is on or after current date": "is on or after current date",
   "is on or before current date": "is on or before current date",
   "is after current date": "is after current date",
   "is before current date": "is before current date",
   "is on or after": "is on or after",
   "is on or before": "is on or before",
   "is after": "is after",
   "is before": "is before",
   "is not": "is not",
   "is": "is",
   "doesn't contain": "doesn't contain",
   "contains": "contains",
   "Not In Data Collection": "Not In Data Collection",
   "In Data Collection": "In Data Collection",
   "Not Field": "Not Field",
   "Same As Field": "Same As Field",
   "Not Same As User": "Not Same As User",
   "Same As User": "Same As User",
   "Choose a Field": "Choose a Field",
   "Choose a Query": "Choose a Query",
   "Not By Query Field": "Not By Query Field",
   "By Query Field": "By Query Field",
   "Not In Query": "Not In Query",
   "In Query": "In Query",
   "This Object": "This Object",
   "Add a filter": "Add a filter",
   "Or": "Or",
   "And": "And",
   "add widgets here": "add widgets here",
   "show icon?": "show icon?",
   "Database field name": "Database field name",
   "Field Name": "Field Name",
   "Label": "Label",
   "Section Name": "Section Name",
   "Section Title": "Section Title",
   "<b>{0}</b> is renamed.": "Rename to <b>{0}</b>.",
   "System could not rename <b>{0}</b>.": "System could not rename <b>{0}</b>.",
   "<b>{0}</b> is deleted.": "<b>{0}</b> is deleted.",
   "System could not delete <b>{0}</b>.": "System could not delete <b>{0}</b>.",
   "<b>{0}</b> is updated.": "<b>{0}</b> is updated.",
   "System could not update <b>{0}</b>.": "System could not update <b>{0}</b>.",
   "<b>{0}</b> is created.": "<b>{0}</b> is created.",
   "System could not create <b>{0}</b>.": "System could not create <b>{0}</b>.",
   "This field is required": "This field is required",
   "Unique": "Unique",
   "Required": "Required",
   "Disable": "Disable",
   "Enter default value": "Enter default value",
   "Default": "Default",
   "Close": "Close",
   "None": "None",
   "No": "No",
   "Yes": "Yes",
   "Save": "Save",
   "Cancel": "Cancel",
   "Ok": "Ok",
   "Rename": "Rename",
   "Import": "Import",
   "Name": "Name",
   "Export": "Export",
   "Edit": "Edit",
   "Delete": "Delete",
   "Create": "Create",
   "Add": "Add",
};
