/* eslint-disable */
module.exports = {
   /* key : label */
   "No template file" : "No template file",
   "is not empty" : "is not empty",
   "is empty" : "is empty",
   'Name must be unique ("{0}" already in use)' : 'Name must be unique ("{0}" already in use)',
   "Column {0}" : "Column {0}",
   "Import {0} Records" : "Import {0} Records",
   "Search records..." : "Search records...",
   "Header on first line" : "Header on first line",
   "Space ( )" : "Space ( )",
   "Semicolon (;)" : "Semicolon (;)",
   "Tab (&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)" : "Tab (&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)",
   "Comma (,)" : "Comma (,)",
   "Separated by" : "Separated by",
   "Choose a CSV file" : "Choose a CSV file",
   "CSV Importer" : "CSV Importer",
   'Object name must be unique ("{0}" already in use)' : 'Object name must be unique ("{0}" already in use)',
   "Field columnName must be unique ({0} already used in this Application)" : "Field columnName must be unique ({0} already used in this Application)",
   "should be greater than {0}" : "should be greater than {0}",
   "%" : "%",
   "€ (after)" : "€ (after)",
   "€ (before)" : "€ (before)",
   "£" : "£",
   "¥" : "¥",
   "$" : "$",
   "minimum column width is {0}" : "minimum column width is {0}",
   "30" : "30",
   "Z -> A" : "Z -> A",
   "A -> Z" : "A -> Z",
   "Please select field" : "Please select field",
   "Add new sort" : "Add new sort",
   "Are you sure you want to delete the selected records?" : "Are you sure you want to delete the selected records?",
   "Delete Multiple Records" : "Delete Multiple Records",
   "Are you sure you want to update the selected records?" : "Are you sure you want to update the selected records?",
   "Updating Multiple Records" : "Updating Multiple Records",
   "Update" : "Update",
   "Search or scan a barcode to see results" : "Search or scan a barcode to see results",
   "Search..." : "Search...",
   "Select an object to load." : "Select an object to load.",
   "Combined Fields" : "Combined Fields",
   "Preview" : "Preview",
   "Length" : "Length",
   "Delimiter" : "Delimiter",
   "US" : "US",
   "Prefix" : "Prefix",
   "Field" : "Field",
   "Count" : "Count",
   "Average" : "Average",
   "Min" : "Min",
   "Max" : "Max",
   "Sum" : "Sum",
   "{Firstname} {Lastname}" : "{Firstname} {Lastname}",
   "Text Formula" : "Text Formula",
   "Number Operators" : "Number Operators",
   "Date Fields" : "Date Fields",
   "Number Fields" : "Number Fields",
   "Equation" : "Equation",
   ") Closed Bracket" : ") Closed Bracket",
   "( Open Bracket" : "( Open Bracket",
   "/ Divides" : "/ Divides",
   " Multiples" : "* Multiples",
   "- Subtracts" : "- Subtracts",
   "+ Adds" : "+ Adds",
   "Space" : "Space",
   "Period" : "Period",
   "Comma" : "Comma",
   "Select index field" : "Select index field",
   "Index Field:" : "Index Field:",
   "Custom Foreign Key" : "Custom Foreign Key",
   "Each <b>#selectedObjLabel#</b> entry connects with" : "Each <b>#selectedObjLabel#</b> entry connects with",
   "<b>#selectedObjLabel#</b> entry." : "<b>#selectedObjLabel#</b> entry.",
   "one" : "one",
   "many" : "many",
   "Connect to new Object" : "Connect to new Object",
   "Select object" : "Select object",
   "Connected to:" : "Connected to:",
   "Show Username" : "Show Username",
   "Show Profile Image" : "Show Profile Image",
   "Editable" : "Editable",
   "Default value as current user" : "Default value as current user",
   "Allow multiple users" : "Allow multiple users",
   "Default image" : "Default image",
   "Height" : "Height",
   "Width" : "Width",
   "txt,rtf,doc,docx,..." : "txt,rtf,doc,docx,...",
   "Type" : "Type",
   "Size (MB)" : "Size (MB)",
   "Select Default" : "Select Default",
   "Add new option" : "Add new option",
   "Options" : "Options",
   "Customize Colors" : "Customize Colors",
   "Multiselect" : "Multiselect",
   "Uncheck" : "Uncheck",
   "Specific Time" : "Specific Time",
   "Current Time" : "Current Time",
   "Default Time" : "Default Time",
   "Time Format" : "Time Format",
   "Ignore Date" : "Ignore Date",
   "Years" : "Years",
   "Months" : "Months",
   "Days" : "Days",
   "Unit" : "Unit",
   "Less than or Equal to" : "Less than or Equal to",
   "Greater than or Equal to" : "Greater than or Equal to",
   "Less than" : "Less than",
   "Greater than" : "Greater than",
   "Not equal to" : "Not equal to",
   "Equal to" : "Equal to",
   "Not between" : "Not between",
   "Between" : "Between",
   "Range" : "Range",
   "Condition" : "Condition",
   "Validation criteria" : "Validation criteria",
   "Specific Date" : "Specific Date",
   "Current Date" : "Current Date",
   "Date Format" : "Date Format",
   "Maximum" : "Maximum",
   "Minimum" : "Minimum",
   "Validation" : "Validation",
   "Thousands" : "Thousands",
   "Round Down" : "Round Down",
   "Round Up" : "Round Up",
   "Rounding" : "Rounding",
   "Places" : "Places",
   "Decimals" : "Decimals",
   "Format" : "Format",
   "Add Field Validation" : "Add Field Validation",
   "Support multilingual" : "Support multilingual",
   "Select a string field" : "Select a string field",
   "Select a number field" : "Select a number field",
   "Select a date field" : "Select a date field",
   "Notes" : "Notes",
   "Progress" : "Progress",
   "Duration" : "Duration",
   "End Date" : "End Date",
   "Start Date" : "Start Date",
   "Title" : "Title",
   "Select a user field" : "Select a user field",
   "Select a field" : "Select a field",
   "Card Owner" : "Card Owner",
   "Horizontal Grouping" : "Horizontal Grouping",
   "Vertical Grouping" : "Vertical Grouping",
   "Click or type to add user..." : "Click or type to add user...",
   "by Account" : "by Account",
   "Click or type to add role..." : "Click or type to add role...",
   "by Role" : "by Role",
   "select a user" : "select a user",
   "select a role" : "select a role",
   "Select which connected object to remove" : "Select which connected object to remove",
   "Remove Connected Record" : "Remove Connected Record",
   "Insert Connected Object" : "Insert Connected Object",
   "How to choose which object:" : "How to choose which object:",
   "Select which connected object to update." : "Select which connected object to update.",
   "Update Connected Record" : "Update Connected Record",
   "Choose select option" : "Choose select option",
   "Choose value from..." : "Choose value from...",
   "Choose a data source" : "Choose a data source",
   "Choose a field" : "Choose a field",
   "A value is required" : "A value is required",
   "Update Record" : "Update Record",
   "Logout" : "Logout",
   "Switcheroo" : "Switcheroo",
   "User Profile" : "User Profile",
   "Logout" : "Logout",
   "Switcheroo" : "Switcheroo",
   "User Profile" : "User Profile",
   "Drag and drop or click here": "Drag and drop or click here",
   "Attach an image to this object.": "Attach an image to this object.",
   "Image Attachment": "Image Attachment",
   "No more tasks...good job!": "No more tasks...good job!",
   "Your Tasks": "Your Tasks",
   "No tasks...you're all caught up.": "No tasks...you're all caught up.",
   "Inbox": "Inbox",
   "OK": "OK",
   "Alert": "Alert",
   "No rows were effected.  This does not seem right.":
      "No rows were effected.  This does not seem right.",
   "Do you want to delete this row?": "Do you want to delete this row?",
   "Delete data": "Delete data",
   " no": " no",
   " yes": " yes",
   "Send a custom email": "Send a custom email",
   "Redirect to another website URL": "Redirect to another website URL",
   "Close the current popup": "Close the current popup",
   "Redirect to the parent page": "Redirect to the parent page",
   "Redirect to an existing page": "Redirect to an existing page",
   "Message": "Message",
   "Show a confirmation message": "Show a confirmation message",
   "Select items": "Select items",
   "Select item": "Select item",
   "Sort": "Apply sort",
   "Filters": "Add filters",
   "Reset Filter": "Reset Filter",
   "To": "To",
   "Set": "Set",
   "Add field to edit": "Add field to edit",
   "Expand Menu": "Expand Menu",
   "Collapse Menu": "Collapse Menu",
   "does not contain current user": "does not contain current user",
   "contains current user": "contains current user",
   "is not current user": "is not current user",
   "is current user": "is current user",
   "is not checked": "is not checked",
   "is checked": "is checked",
   "does not equal": "does not equal",
   "equals": "equals",
   "≥": "≥",
   "≤": "≤",
   ">": ">",
   "<": "<",
   "≠": "≠",
   ":": "=",
   "next ... days": "next ... days",
   "last ... days": "last ... days",
   "is on or after current date": "is on or after current date",
   "is on or before current date": "is on or before current date",
   "is after current date": "is after current date",
   "is before current date": "is before current date",
   "is on or after": "is on or after",
   "is on or before": "is on or before",
   "is after": "is after",
   "is before": "is before",
   "is not": "is not",
   "is": "is",
   "doesn't contain": "doesn't contain",
   "contains": "contains",
   "Not In Data Collection": "Not In Data Collection",
   "In Data Collection": "In Data Collection",
   "Not Field": "Not Field",
   "Same As Field": "Same As Field",
   "Not Same As User": "Not Same As User",
   "Same As User": "Same As User",
   "Choose a Field": "Choose a Field",
   "Choose a Query": "Choose a Query",
   "Not By Query Field": "Not By Query Field",
   "By Query Field": "By Query Field",
   "Not In Query": "Not In Query",
   "In Query": "In Query",
   "This Object": "This Object",
   "Add a filter": "Add a filter",
   "Or": "Or",
   "And": "And",
   "add widgets here": "add widgets here",
   "show icon?": "show icon?",
   "Database field name": "Database field name",
   "Field Name": "Field Name",
   "Label": "Label",
   "Section Name": "Section Name",
   "Section Title": "Section Title",
   "<b>{0}</b> is renamed.": "Rename to <b>{0}</b>.",
   "System could not rename <b>{0}</b>.": "System could not rename <b>{0}</b>.",
   "<b>{0}</b> is deleted.": "<b>{0}</b> is deleted.",
   "System could not delete <b>{0}</b>.": "System could not delete <b>{0}</b>.",
   "<b>{0}</b> is updated.": "<b>{0}</b> is updated.",
   "System could not update <b>{0}</b>.": "System could not update <b>{0}</b>.",
   "<b>{0}</b> is created.": "<b>{0}</b> is created.",
   "System could not create <b>{0}</b>.": "System could not create <b>{0}</b>.",
   "This field is required": "This field is required",
   "Unique": "Unique",
   "Required": "Required",
   "Disable": "Disable",
   "Enter default value": "Enter default value",
   "Default": "Default",
   "Close": "Close",
   "None": "None",
   "No": "No",
   "Yes": "Yes",
   "Save": "Save",
   "Cancel": "Cancel",
   "Ok": "Ok",
   "Rename": "Rename",
   "Import": "Import",
   "Name": "Name",
   "Export": "Export",
   "Edit": "Edit",
   "Delete": "Delete",
   "Create": "Create",
   "Add": "Add",
};
