name: Dispatch Updates
on:
  workflow_call:
    inputs:
      version:
        description: The updated version of core
        type: string
        required: true

jobs:
  dispatch-update-services:
    name: Dispatch Update Services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependant:
          # - ab_platform_web
          - ab_platform_service
      steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v2
          env: 
            VERS: ${{ inputs.version }}
          with:
            token: ${{ secrets.PAT }}
            repository: digi-serve/${{ matrix.dependant }}
            event-type: core_new_version
            client-payload: '{"type": "patch", "version": "${{ env.VERS }}"}'
