name: Dispatch Updates
on:
  workflow_call:
    inputs:
      version:
        description: The updated version of core
        type: string
        required: true
    secrets:
      TOKEN:
        required: true

jobs:
  dispatch-update-platforms:
    name: Dispatch Update Platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - ab_platform_web
          - appbuilder_platform_service
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        env: 
          VERS: ${{ inputs.version }}
        with:
          token: ${{ secrets.TOKEN }}
          repository: digi-serve/${{ matrix.platform }}
          event-type: core_new_version
          client-payload: '{"type": "patch", "version": "${{ env.VERS }}"}'
