name: Cypress E2E Tests
on:
  workflow_call:
jobs:
  test:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    env:
      CYPRESS_RESPONSE_TIMEOUT: 200000
      CYPRESS_DEFAULT_COMMAND_TIMEOUT: 30000
      CYPRESS_RETRIES: 2
    steps:
      # Checkout each service that uses subrepo AppBuilder then core inside it
      # ab_service_appbuilder,
      - name: Checkout ab_service_appbuilder
        uses: actions/checkout@v3
        with:
          path: ab_service_appbuilder
          repository: digi-serve/ab_service_appbuilder
          submodules: true
      - name: Checkout ab_service_appbuilder > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_appbuilder/AppBuilder/core
      # ab_service_custom_reports
      - name: Checkout ab_service_custom_reports
        uses: actions/checkout@v3
        with:
          path: ab_service_custom_reports
          repository: digi-serve/ab_service_custom_reports
          submodules: true
      - name: Checkout ab_service_custom_reports > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_custom_reports/AppBuilder/core
      # ab_service_definition_manager
      - name: Checkout ab_service_definition_manager
        uses: actions/checkout@v3
        with:
          path: ab_service_definition_manager
          repository: digi-serve/ab_service_definition_manager
          submodules: true
      - name: Checkout ab_service_definition_manager > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_definition_manager/AppBuilder/core
      # ab_service_file_processor
      - name: Checkout ab_service_file_processor
        uses: actions/checkout@v3
        with:
          path: ab_service_file_processor
          repository: digi-serve/ab_service_file_processor
          submodules: true
      - name: Checkout ab_service_file_processor > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_file_processor/AppBuilder/core
      # ab_service_process_manager
      - name: Checkout ab_service_process_manager
        uses: actions/checkout@v3
        with:
          path: ab_service_process_manager
          repository: digi-serve/ab_service_process_manager
          submodules: true
      - name: Checkout ab_service_process_manager > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_process_manager/AppBuilder/core
      # ab_service_user_manager
      - name: Checkout ab_service_user_manager
        uses: actions/checkout@v3
        with:
          path: ab_service_user_manager
          repository: digi-serve/ab_service_user_manager
          submodules: true
      - name: Checkout ab_service_user_manager > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_user_manager/AppBuilder/core
      # Checkout ab_platform_web and build new app.js
      - name: Checkout ab_platform_web
        uses: actions/checkout@v3
        with:
          path: ab_platform_web
          repository: digi-serve/ab_platform_web
      - name: Checkout ab_platform_web > core
        uses: actions/checkout@v3
        with:
          path: ab_platform_web/AppBuilder/core
      - name: Checkout ab_service_web
        uses: actions/checkout@v3
        with:
          path: web
          repository: digi-serve/ab_service_web      
      - run: npm i
        working-directory: ./ab_platform_web
      - name: Webpack
        run: npm run build:update
        working-directory: ./ab_platform_web
      # webpack expects the folder to be called "web" ab-install action expects "ab_service_web"
      - run: mv web ab_service_web
      # install and test   
      - name: Install AppBuilder
        uses: digi-serve/ab-install-action@v1
      - name: Check out kitchen-sink tests
        uses: actions/checkout@v2
        with:
          repository: digi-serve/kitchensink_app
          path: AppBuilder/test/e2e/cypress/e2e/kitchensink_app
      # These next steps are to save our ablogs to file
      - run: npm install pm2@latest -g
      - name: Save Logs
        run: pm2 start ./logs.js -- --toFile logs/ABServices.log
        working-directory: ./AppBuilder
      - name: Wait for AB
        # Skipping the wait step. Cypress has a bit of wait time built in. It might be enough.
        if: false
        uses: ifaxity/wait-on-action@v1.1.0
        with:
          resource: http://localhost:80
          timeout: 300000
      - name: Run Cypress Tests
        run: npm run test:e2e:app -- --browser chrome
        working-directory: ./AppBuilder
      - name: Save Screenshots 
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./AppBuilder/test/e2e/cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ABServices.log
          path: ./AppBuilder/logs/ABServices.log
          
