
name: Test and Update
on:
  # Run on any commit to the #master branch
  push:
    branches: [v2]
  # Run on pull requests into the #master branch
  pull_request:
    branches: [v2]
jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      CYPRESS_RESPONSE_TIMEOUT: 200000
      CYPRESS_DEFAULT_COMMAND_TIMEOUT: 30000
      CYPRESS_RETRIES: 2
    steps:
      # Checkout each service that uses subrepo AppBuilder then core inside it
      # ab_service_appbuilder,
      - name: Checkout ab_service_appbuilder
        uses: actions/checkout@v3
        with:
          path: ab_service_appbuilder
          repository: digi-serve/ab_service_appbuilder
          submodules: true
          ref: develop
      - name: Checkout ab_service_appbuilder > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_appbuilder/AppBuilder/core
      # ab_service_custom_reports
      - name: Checkout ab_service_custom_reports
        uses: actions/checkout@v3
        with:
          path: ab_service_custom_reports
          repository: digi-serve/ab_service_custom_reports
          submodules: true
          ref: develop
      - name: Checkout ab_service_custom_reports > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_custom_reports/AppBuilder/core
      # ab_service_definition_manager
      - name: Checkout ab_service_definition_manager
        uses: actions/checkout@v3
        with:
          path: ab_service_definition_manager
          repository: digi-serve/ab_service_definition_manager
          submodules: true
          ref: develop
      - name: Checkout ab_service_definition_manager > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_definition_manager/AppBuilder/core
      # ab_service_file_processor
      - name: Checkout ab_service_file_processor
        uses: actions/checkout@v3
        with:
          path: ab_service_file_processor
          repository: digi-serve/ab_service_file_processor
          submodules: true
          ref: develop
      - name: Checkout ab_service_file_processor > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_file_processor/AppBuilder/core
      # ab_service_process_manager
      - name: Checkout ab_service_process_manager
        uses: actions/checkout@v3
        with:
          path: ab_service_process_manager
          repository: digi-serve/ab_service_process_manager
          submodules: true
          ref: develop
      - name: Checkout ab_service_process_manager > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_process_manager/AppBuilder/core
      # ab_service_user_manager
      - name: Checkout ab_service_user_manager
        uses: actions/checkout@v3
        with:
          path: ab_service_user_manager
          repository: digi-serve/ab_service_user_manager
          submodules: true
          ref: develop
      - name: Checkout ab_service_user_manager > AppBuilder > core
        uses: actions/checkout@v3
        with:
          path: ab_service_user_manager/AppBuilder/core
      # Checkout ab_platform_web and build new app.js
      - name: Checkout ab_platform_web
        uses: actions/checkout@v3
        with:
          path: ab_platform_web
          repository: digi-serve/ab_platform_web
      - name: Checkout ab_platform_web > core
        uses: actions/checkout@v3
        with:
          path: ab_platform_web/AppBuilder/core
      - name: Checkout ab_service_web
        uses: actions/checkout@v3
        with:
          path: web
          repository: digi-serve/ab_service_web      
      - run: npm i
        working-directory: ./ab_platform_web
      - name: Webpack
        run: npm run build:update
        working-directory: ./ab_platform_web
      # webpack expects the folder to be called "web" ab-install action expects "ab_service_web"
      - run: mv web ab_service_web
      # install and test   
      - name: Install AppBuilder
        uses: digi-serve/ab-install-action@v1
      - name: Check out kitchen-sink tests
        uses: actions/checkout@v2
        with:
          repository: digi-serve/kitchensink_app
          path: AppBuilder/test/e2e/cypress/e2e/kitchensink_app
      - name: Wait for AB
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:80
          timeout: 300000
      - name: Run Cypress Tests
        run: npm run test:e2e:app -- --browser chrome
        working-directory: ./AppBuilder
      - name: Save Screenshots 
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./AppBuilder/test/e2e/cypress/screenshots
  update-platform-service:
    name: Update appbuilder_platform_service
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }} 
    steps:
      - name: Checkout appbuilder_platform_service
        uses: actions/checkout@v3
        with:
          repository: digi-serve/appbuilder_platform_service
          path: appbuilder_platform_service
          ref: master
          fetch-depth: 0 
          token: ${{ secrets.DS_REPO_PAT }}
          submodules: recursive
      - name: Checkout core@v2
        run: git checkout v2
        working-directory: appbuilder_platform_service/core
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update core sub-repo (from GitHub Actions)'
          cwd: appbuilder_platform_service
  update-platform-web:
    name: Update ab_platform_web
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }} 
    steps:
      - name: Checkout ab_platform_web
        uses: actions/checkout@v3
        with:
          repository: digi-serve/ab_platform_web
          path: ab_platform_web
          ref: master
          fetch-depth: 0 
          token: ${{ secrets.DS_REPO_PAT }}
          submodules: recursive
      - name: Checkout core@v2
        run: git checkout v2
        working-directory: ab_platform_web/AppBuilder/core
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update core sub-repo (from GitHub Actions)'
          cwd: ab_platform_web
